import { Doctor } from '@/components/ui/DoctorCard'

export const ALL_DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Samuel Bekele',
    subtitle: 'Black Lion Hospital, Ethiopia',
    specialty: 'Neurologist',
    rating_average: 5.0,
    review_count: 243,
    years_experience: 14,
    bio: 'Dr. Samuel Bekele is a board-certified neurologist specializing in stroke, epilepsy, and neurodegenerative diseases. He has published over 20 research papers and is committed to providing world-class neurological care.',
    chat_price: 250,
    phone_price: 320,
    video_price: 500,
    is_online: false,
    profile_photo_url: null,
  },
  {
    id: '2',
    name: 'Dr. Eleni Tesfaye',
    subtitle: 'Tikur Anbessa Hospital, Ethiopia',
    specialty: 'General Practitioner',
    rating_average: 4.9,
    review_count: 112,
    years_experience: 10,
    bio: 'Dr. Eleni Tesfaye is a compassionate and experienced general practitioner providing comprehensive primary care. She focuses on preventive medicine and patient education.',
    chat_price: 100,
    phone_price: 150,
    video_price: 300,
    is_online: true,
    profile_photo_url: null,
  },
  {
    id: '3',
    name: 'Dr. Fatima Al-Rashid',
    subtitle: 'American Hospital, UAE',
    specialty: 'Psychiatrist',
    rating_average: 4.9,
    review_count: 189,
    years_experience: 12,
    bio: 'Dr. Fatima Al-Rashid is a renowned psychiatrist with expertise in anxiety, depression, and trauma-focused therapies. She provides culturally sensitive mental health care.',
    chat_price: 180,
    phone_price: 230,
    video_price: 400,
    is_online: true,
    profile_photo_url: null,
  },
  {
    id: '4',
    name: 'Dr. Mark Wilson',
    subtitle: 'Dermacare Clinic, USA',
    specialty: 'Dermatologist',
    rating_average: 4.8,
    review_count: 95,
    years_experience: 9,
    bio: 'Dr. Mark Wilson specializes in medical and cosmetic dermatology, treating skin conditions from acne to psoriasis with evidence-based and minimally invasive approaches.',
    chat_price: 150,
    phone_price: 200,
    video_price: 380,
    is_online: true,
    profile_photo_url: null,
  },
  {
    id: '5',
    name: 'Dr. Kidist Alemu',
    subtitle: 'St. Paul\'s Hospital, Ethiopia',
    specialty: 'Orthopedic Surgeon',
    rating_average: 4.8,
    review_count: 156,
    years_experience: 16,
    bio: 'Dr. Kidist Alemu is an orthopedic surgeon with a focus on sports injuries, joint replacement, and bone health. She is a pioneer in minimally invasive surgical techniques in Ethiopia.',
    chat_price: 220,
    phone_price: 280,
    video_price: 450,
    is_online: false,
    profile_photo_url: null,
  },
  {
    id: '6',
    name: 'Dr. Jean-Pierre Nshimiye',
    subtitle: 'King Faisal Hospital, Rwanda',
    specialty: 'Pediatrician',
    rating_average: 4.7,
    review_count: 81,
    years_experience: 8,
    bio: 'Dr. Jean-Pierre Nshimiye is a dedicated pediatrician focused on child development, immunizations, and managing childhood illnesses with a family-centered approach.',
    chat_price: 130,
    phone_price: 180,
    video_price: 320,
    is_online: true,
    profile_photo_url: null,
  },
  {
    id: '7',
    name: 'Dr. Amina Hassan',
    subtitle: 'Mogadishu Teaching Hospital, Somalia',
    specialty: 'Cardiologist',
    rating_average: 4.6,
    review_count: 67,
    years_experience: 11,
    bio: 'Dr. Amina Hassan is a cardiologist specializing in preventive cardiology, heart failure management, and non-invasive cardiac imaging.',
    chat_price: 200,
    phone_price: 260,
    video_price: 450,
    is_online: true,
    profile_photo_url: null,
  },
  {
    id: '8',
    name: 'Dr. Yonas Haile',
    subtitle: 'Yekatit 12 Hospital, Ethiopia',
    specialty: 'Dermatologist',
    rating_average: 4.8,
    review_count: 134,
    years_experience: 7,
    bio: 'Dr. Yonas Haile is a young and skilled dermatologist specializing in skin infections, pigmentation disorders, and cosmetic dermatology.',
    chat_price: 160,
    phone_price: 210,
    video_price: 360,
    is_online: true,
    profile_photo_url: null,
  },
]

export const MOCK_REVIEWS = [
  {
    id: 'r1',
    patientName: 'Hana M.',
    rating: 5,
    comment: 'Very professional and caring. Explained everything clearly and followed up after the consultation.',
    date: '2 days ago',
  },
  {
    id: 'r2',
    patientName: 'Abebe T.',
    rating: 5,
    comment: 'Excellent experience! The doctor was very knowledgeable and answered all my questions patiently.',
    date: '1 week ago',
  },
  {
    id: 'r3',
    patientName: 'Meron K.',
    rating: 4,
    comment: 'Good consultation. The doctor was thorough and the video call quality was great.',
    date: '2 weeks ago',
  },
]

export const SPECIALTIES = [
  'All Specialties',
  'General Practitioner',
  'Dermatologist',
  'Pediatrician',
  'Neurologist',
  'Psychiatrist',
  'Cardiologist',
  'Orthopedic Surgeon',
]
